import Head from "next/head";
import Image from "next/image";
import RoundBtn from "../components/RoundBtn/RoundBtn";
import TopNavigation from "../components/TopNavigation/TopNavigation";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
      </Head>
      <main className={styles.Home}>
        <div style={{ display: "flex", justifyContent: "space-around" }}>
          <div style={{ width: "450px" }}>
            <h5
              style={{
                color: "var(--secondary-color)",
                textTransform: "uppercase",
              }}
            >
              So, you want to travel to:
            </h5>
            <h1
              style={{
                color: "#fff",
                textTransform: "uppercase",
                margin: "0 0 22 0",
              }}
            >
              Space
            </h1>
            <p style={{ color: "#fff" }}>
              Let’s face it; if you want to go to space, you might as well
              genuinely go to outer space and not hover kind of on the edge of
              it. Well sit back, and relax because we’ll give you a truly out of
              this world experience!
            </p>
          </div>
          <RoundBtn />
        </div>
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}
